[bastion]
3.67.220.203 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/id_rsa

[webservers]
10.0.1.238 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ec2-user@3.67.220.203 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no"'