---
- name: Web szerver beállítása
  hosts: all  # <--- Itt CSAK a webservers csoportra szűrünk!
  become: yes
  vars:
    app_name: "2048 Játék"
    github_repo: "https://github.com/gabrielecirulli/2048.git"
    dest_path: "/var/www/html/2048"

  tasks:
    - name: Apache és Git telepítése egyszerre
      yum:
        name: 
          - httpd
          - git
        state: present

    - name: Apache elindítása
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Alkalmazás letöltése a repóból
      git:
        repo: "{{ github_repo }}"
        dest: "{{ dest_path }}"
        version: master

    - name: Egyedi kezdőlap létrehozása változóval
      copy:
        content: "<h1>Markosz DevOps Szervere - Ez a {{ app_name }} projekt.</h1><a href='/2048/'>Kattints ide!</a>"
        dest: /var/www/html/index.html